### PR TITLE
Don't fail on bad/missing update feed URL.

### PR DESCRIPTION
**Pull request by barnson**

### CODE REVIEW

**Comment by robmen** [comment]
I must be missing something. Is there a change to wixstdba or burn needed?

**Comment by barnson** [comment]
Test-driven development. I'm making sure the new test fails without the fix. (I've validated manually by hand but wanted a new test to run.)

**Comment by barnson** [comment]
And, of course, there are no failures. 🥇

**Comment by barnson** [comment]
Fixes https://github.com/wixtoolset/issues/issues/7090.

**Pull request merged**
