### PR TITLE
Add runtime testing for #6705

### PR DESCRIPTION
**Pull request by rseanhall**

### CODE REVIEW

**Comment by rseanhall** [comment]
The builds are getting automatically canceled and I can't tell why.

**Comment by robmen** [comment]
So, given the progress, I guess the VS install either needs to restart the computer or our configuration step isn't actually waiting for the install to complete.

**Comment by rseanhall** [comment]
I'm not sure. The initial steps are still taking way too long. I reenabled AppVeyor for now.

**Comment by robmen** [comment]
Oh, I definitely spoke to soon. Given the way my week is going... not surprising. :(

**Comment by rseanhall** [comment]
My hypothesis build failed because they still don't have the v141 toolset for us. It might have completed successfully, but it feels like the machine is very low on either memory or disk space considering how long it takes for things that should be fast like running the VS initialization script.

**Comment by rseanhall** [comment]
Looks like AppVeyor is rebasing or merging my branch with the latest, which is failing due to problems fixed in Rob's PR. We should probably figure out how to get Github Actions to do that, though I had hoped to use that fact that it doesn't to my advantage here.

**Comment by rseanhall** [comment]
Close and reopen to trigger Appveyor.

**Comment by rseanhall** [comment]
Appveyor build passed: https://ci.appveyor.com/project/wixtoolset/wix4/builds/42515706

**Pull request merged**
