### PR TITLE
Use VS2022 build image

### PR DESCRIPTION
**Pull request by rseanhall**
Update v4.0 projects to target v4.7.2.
Skip all Bal managed host tests, tracked in https://github.com/wixtoolset/issues/issues/6651.

### CODE REVIEW

**Comment by rseanhall** [comment]
Weird. This worked on Appveyor - https://ci.appveyor.com/project/SeanHall/wix4/builds/41790360

**Comment by barnson** [comment]
Hey, this all looks familiar...I'm assuming AppVeyor's image has the reference assemblies installed (somehow).

**Comment by rseanhall** [comment]
It does not, that's why I had to retarget to v4.7.2.

**Comment by rseanhall** [comment]
I incorporated Bob's changes to only use v143 since the Github build machine doesn't seem to have any other toolset. Not sure if we actually want to do this or not. Or maybe start ignoring Github builds again and rely on Appveyor's until Github has the toolsets that we need?

**Comment by barnson** [comment]
This means DTF can't be used by earlier targets?

**Comment by rseanhall** [comment]
No, only test projects were retargeted. None of my changes affects shipped code, unless you count building it with VS2022 instead of VS2019.

**Comment by barnson** [comment]
Cool.

**Comment by rseanhall** [comment]
The build worked, so I guess it's time to install VS2022 locally. Still not sure what to do with this PR.

**Pull request closed without merging**
