### PR TITLE
Update MSBuildRunner to ignore previous VS versions

### PR DESCRIPTION
**Pull request by cpuwzd**
Update MSBuildRunner so that build can succeed when VS 2019 is present in addition to VS 2022

### CODE REVIEW

**Comment by cpuwzd** [comment]
recheck

**Comment by cpuwzd** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by cpuwzd** [comment]
recheck

**Comment by robmen** [comment]
Woot! Thank you.

**Pull request merged**
