### PR TITLE
Handle 32-bit related-bundle registration...

### PR DESCRIPTION
**Pull request by barnson**
...from 64-bit bundles.

### CODE REVIEW

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/6670

**Comment by barnson** [comment]
Oh. Right. A 64-bit BA.

**Comment by rseanhall** [comment]
https://github.com/wixtoolset/wix4/blob/ed3b31d4120febbfe51146c138d145e826926b39/src/test/burn/TestData/BasicFunctionalityTests/BundleB_x64/BundleB_x64.wixproj#L5

**Comment by barnson** [comment]
Nice, thanks. I assumed it was there, somewhere. :)

**Comment by rseanhall** [comment]
I completely forgot about this, but due to https://github.com/wixtoolset/issues/issues/6464 you need this too:

https://github.com/wixtoolset/wix4/blob/ed3b31d4120febbfe51146c138d145e826926b39/src/test/burn/TestData/BasicFunctionalityTests/BundleB_x64/BundleB_x64.wixproj#L15

**Pull request merged**
