### PR TITLE
Fix bug when parsing bal prereq attributes

### PR DESCRIPTION
**Pull request by rseanhall**
Fixes https://github.com/wixtoolset/issues/issues/7287

### CODE REVIEW

**Comment by rseanhall** [comment]
@robmen @barnson Are we still merging our own pull requests?

**Comment by robmen** [comment]
Normally, yes, but given we're locking down for RTM, the new question is: Does the bug meet the RTM bar?

We haven't discussed the bar yet, so I don't know what the answer is at this moment. One option is to wait for Thursday to evaluate.

**Comment by rseanhall** [comment]
That sure sounds like a no.

**Comment by robmen** [comment]
I waffle (especially if there are unit tests to validate). @barnson tends to be more hardcore than me. 😄

**Comment by barnson** [comment]
Unit tests add +1. There's a workaround, so -1. We'd need to add "known-and-dumb bugs" to track workarounds like this, so +0.5. So I'm net +0.5 to fix.

**Pull request merged**
