### PR TITLE
Add keyColumn definition to _User of Wix4FileSharePermissions

### PR DESCRIPTION
**Pull request by fyodorkor**
This is a fix for issue #7202 I have opened

### CODE REVIEW

**Comment by fyodorkor** [comment]
have read the CLA Document and I hereby sign the CLA

**Comment by fyodorkor** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fyodorkor** [comment]
recheck

**Comment by barnson** [comment]
Fixes https://github.com/wixtoolset/issues/issues/7202.

**Comment by barnson** [comment]
Thanks!

**Pull request merged**
